sensor:
  - platform: niu
    email: !secret niu_email
    password: !secret niu_password
    country : !secret niu_country
    scooter_id : '0'
    monitored_variables:  
    - BatteryCharge
    - Isconnected 
    - TimesCharged 
    - temperatureDesc
    - Temperature
    - BatteryGrade
    - CurrentSpeed
    - ScooterConnected
    - IsCharging
    - IsLocked
    - TimeLeft
    - EstimatedMileage
    - centreCtrlBatt
    - HDOP
    - Distance
    - RidingTime
    - totalMileage
    - DaysInUse
