sensor:
  - platform: niu
    email: !secret niu_email
    password: !secret niu_password
    country : !secret niu_country
    scooter_id : '0'
    monitored_variables:
    - BatteryCharge         #Battery
    - Isconnected           #Battery
    - TimesCharged          #Battery
    - temperatureDesc       #Battery
    - Temperature           #Battery
    - BatteryGrade          #Battery
    - CurrentSpeed          #Moto
    - ScooterConnected      #Moto
    - IsCharging            #Moto
    - IsLocked              #Moto
    - TimeLeft              #Moto
    - EstimatedMileage      #Moto
    - centreCtrlBatt        #Moto
    - HDOP                  #Moto
    - Longitude             #Moto
    - Latitude              #Moto
    - totalMileage          #OverAll
    - DaysInUse             #OverAll
    - Distance              #Distance
    - RidingTime            #Distance
    - LastTrackStartTime    #LastTrack
    - LastTrackEndTime      #LastTrack
    - LastTrackDistance     #LastTrack
    - LastTrackAverageSpeed #LastTrack
    - LastTrackRidingtime   #LastTrack
